version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - app-network

  web-app:
    build:
      context: .
      dockerfile: ProcessMappingApi/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sql-server
    environment:
      ConnectionStrings__DefaultConnection: "Server=sql-server,1433; Database=ProcessMapingDb; User Id=sa; Password=Password1; Trust Server Certificate=True;"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
